attributes:
    
    recipeId: 
        primaryKey:    true
        type:          INTEGER
        autoIncrement: true

    recipeTitle:
        type: STRING

    recipeCookingTime:
        type: INTEGER

